### ISSUE TITLE
Upgrade mongo driver to 2.2.2

### ISSUE THREAD

**Issue by smtlaissezfaire** [mongomapper/mongomapper#631] opened 2016-01-13 23:20 UTC
This way we can support mongo 3.2:

https://docs.mongodb.org/ecosystem/drivers/ruby/

This should also fix bugs re: connection string.

**Comment by cheald** [comment] 2016-01-14 03:41
The 2.x driver is a ground-up rewrite that's basically custom-built to support Mongoid. MongoMapper will need significant and substantial changes to support it.

**Comment by smtlaissezfaire** [comment] 2016-01-14 03:49
Hmm - I guess the bigger changes will be in plucky, not in MM directly.

**Comment by jamieorc** [comment] 2016-03-30 18:08
Oh man, so Mongodb 3.2 doesn't support Ruby driver 1.x? Bad news. Is it reasonable to expect MM to get updated to use the 2.2 driver?

**Comment by cheald** [comment] 2016-03-30 18:09
Yikes. Dat compatibility drop.

I guess we're forced to go ahead and support it, then. It's going to be a major version bump with a significant change to how connections are handled, at a minimum.

**Comment by fcheung** [comment] 2016-04-04 11:08
Happy to help out here - in the same boat here in that we'd obviously like to switch to 3.2 at some point (although we don't necessarily need all the new features). I've written code that uses the 2.x driver directly so I have at least some familiarity with it but pretty ignorant of mm / plucky internals.

**Comment by jamieorc** [comment] 2016-04-04 13:48
I took a quick look at Plucky over the weekend, but wasn’t really in the mind-frame to absorb much. I’m pretty stretched, but if I can, I’ll help out. 

Jamie

**Comment by fcheung** [comment] 2016-04-04 21:43
I made a start on plucky: https://github.com/mongomapper/plucky/pull/47

**Comment by smtlaissezfaire** [comment] 2016-04-04 22:01
This is great @fchung.  I'll have to take a look at the patch (cc: @cheald)

**Comment by fcheung** [comment] 2016-04-05 19:37
I've also got most of the mongomapper test suite passing: #638

**Comment by fcheung** [comment] 2016-04-26 13:19
I've not had much time to continue working on this, but if anyone had time to spare to help review or offer some opinions on the 2 PRs I've opened that would be very handy. Thanks!

**Comment by jamieorc** [comment] 2016-11-07 02:49
WRT development environments, this is major:

https://docs.mongodb.com/v3.0/reference/program/mongorestore/

```
MAC OSX SIERRA AND GO 1.6 INCOMPATIBILITY
Users running on Mac OSX Sierra require the 3.2.10 or newer version of mongorestore.
```

**Comment by smtlaissezfaire** [comment] 2016-12-08 19:00
Ok - yeah, I agree this is a high priority bug.  I'm going to look at it this weekend.

**Comment by fcheung** [comment] 2016-12-08 19:37
For what it's worth, I've been running the current gem release of mongo mapper (with the 1.x driver) in development for some months now (there are still some performance regressions in 2.x, e.g. https://jira.mongodb.org/browse/RUBY-1144). Hardly a comfortable situation though

**Comment by jamieorc** [comment] 2016-12-08 20:04
This performance regression is rather stunning, both for serialization and deserialization. Given how much data my apps process each night and how large some of our docs are, this could be a major problem for us. Thanks for posting that and the work on the POC.

**Comment by smtlaissezfaire** [comment] 2016-12-11 00:05
@cheald wdyt of the idea combining plucky + mongomapper into one repo?

**Comment by jamieorc** [comment] 2017-03-07 15:44
Is there any movement on this? Mongodb is now on 3.4 and we are stuck on 3.0 until MM supports the new driver. I'm actually busier at my job than last year, so have no personal time to devote to this, myself.

**Comment by fcheung** [comment] 2017-03-07 16:50
This was a while ago, but I did have nearly all of the plucky / mongomapper test suite green against the 2.x driver but I didn't really understand the remaining failures

**Comment by dvergeylen** [comment] 2017-08-01 08:20
Hi @fcheung ,

As you seem busy right now with commits and clean ups, do you think you will take some time soon to solve this issue?

I added support for RethinkDB also (in a personal fork), but couldn't make a pull request because of this limitation.

**Comment by fcheung** [comment] 2017-08-01 11:03
specs in #638 are passing, working on getting some of my apps up and running.

Even when I'm done, upgrading will involve work - any time you're passing driver level options or dropping down to driver level you might to make changes

**Comment by fcheung** [comment] 2017-08-05 18:07
I'm working my way through apps I maintain. So the spec failures have largely been down to where I'd been using the driver directly - I haven't found only mongomapper related howlers yet. More feedback would be very welcome!

**Comment by CFWLoader** [comment] 2017-08-21 04:09
Hi @fcheung 
I'm using mongo_mapper 0.14.0 version(spec file specifies mongo driver version ~> 1.8). And gems determined the mongo driver version to 1.12. Now the mongo driver 1.12 cannot support 'upsert' option. I think that update the dependency of mongo driver can fix this problem. There is mongo driver 2.4.3 in my gems but I can't force mongo_mapper to use it. So I hope you can fix this problem or tell me how to solve it. Thank you very much!

**Comment by fcheung** [comment] 2017-08-21 13:05
Hi,

You're welcome to try my branch from #638, but please be aware that this is still rough around the edges (and that the upgrade from mongo 1.x will likely be rocky)

**Comment by CFWLoader** [comment] 2017-08-22 13:11
Yeah, I found it's a bit hard. I have to find another way to fix this problem. Whatever, thanks for your help!

**Comment by a2ikm** [comment] 2022-08-30 13:45
Hi folks,

mongo_mapper >= 0.15.0 now supports mongo ~> 2.0 and MongoDB 4.0, 4.2, 4.4 and 5.0 thanks to @fcheung's branch and @smtlaissezfaire's commits. It works fine with apps I work for in production.

So please let me close this issue.
If you have any other issues, please file it as another one.

Thank you!

**Closed by a2ikm** 2022-08-30 13:45 UTC

**Comment by jamieorc** [comment] 2022-10-11 07:26
That’s great!

Jamie
